# Generated by Django 3.1.4 on 2020-12-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='id',
            field=models.IntegerField(db_column='FId', primary_key=True, serialize=False),
        ),
    ]
